//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rx
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string patientName { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public string ClinicName { get; set; }
        public string PatientMobile { get; set; }
        public string Date { get; set; }
        public string DoctorName { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string medicineName { get; set; }
        public string dose { get; set; }
    }
}
